### ISSUE TITLE
USB HID instead of MSD? 

### ISSUE THREAD

**Issue by zavodnyrichard** [johnnydrazzi/USB-uC#2]
Would it be possible to use HID instead of MSD? What would I need to modify?

**Comment by johnnydrazzi** [comment]
Hey,
you're better off using or modifying microchips bootloader which uses HID. My code for MSD bootloader wouldn't be of any use for HID.. Head over to [here](https://www.microchip.com/mla) and download the latest MLA. When you've downloaded it, install MLA with USB apps selected, go to the directory apps>usb>device>bootloaders and find information, the firmware and utilities for programming there.

Hope that helps :).
