### ISSUE TITLE
PIC18F25K50 at O2 compile optimization in MPLAB X IDE

### ISSUE THREAD

**Issue by frank9876** [johnnydrazzi/USB-uC#6]
I'm using MPLAB X IDE v6.20 with XC8 v2.48.  I do not have a compiler license so I cannot compile with -Os.
I tried compiling the bootloader for the Pololu P-Star PIC18F25K50.  It does not fit in 8K.
I can program the pre-compiled hex file - USB_uC_X5K50_P_STAR.hex - and that works.
However, I wanted to be able to compile my own binary and the compilation is too large by approximately 120 bytes.
After looking at the code, I re-wrote the routine parse_hex in bootloader.c and the compilation now fits in 8K (approx. 8177 bytes).
My changes are shown with #if 0/1 in bootloader.c in case anyone else is interested in getting the bootloader to build with the standard MPLAB X IDE.
[bootloader_c.zip](https://github.com/user-attachments/files/15903942/bootloader_c.zip)

**Comment by johnnydrazzi** [comment]
Excellent, I’ll take a look when I get the chance and merge your changes.

**Comment by johnnydrazzi** [comment]
I have updated the bootloader.c file using your suggestions in v1.13. This is now compiling using free license. Thanks for opening this issue.
